export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENT_LOADING = 'ADD_COMMENT';
export const COMMENT_FAILED = 'COMMENT_FALED';


export const CAMPSITES_LOADING = 'ADD_CAMPSITE';
export const CAMPSITES_LOADING = 'CAMPSITES_FAILED';
export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';


export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';